// src/App.jsx
import { useEffect, useState, useRef, useCallback } from 'react';

import Progress from './components/Progress';
import MediaInput from './components/MediaInput';
import Transcript from './components/Transcript';
import LanguageSelector from './components/LanguageSelector';


async function hasWebGPU() {
    if (!navigator.gpu) {
        return false;
    }
    try {
        const adapter = await navigator.gpu.requestAdapter();
        return !!adapter;
    } catch (e) {
        return false;
    }
}

function App() {

    // Create a reference to the worker object.
    const worker = useRef(null);

    // Model loading and progress
    const [status, setStatus] = useState(null);
    const [loadingMessage, setLoadingMessage] = useState('');
    const [progressItems, setProgressItems] = useState([]);

    const mediaInputRef = useRef(null);
    const [audio, setAudio] = useState(null);
    const [language, setLanguage] = useState('en');

    const [result, setResult] = useState(null);
    const [time, setTime] = useState(null);
    const [currentTime, setCurrentTime] = useState(0);

    const [device, setDevice] = useState('webgpu'); // Try use WebGPU first
    const [modelSize, setModelSize] = useState('gpu' in navigator ? 196 : 77); // WebGPU=196MB, WebAssembly=77MB
    useEffect(() => {
        hasWebGPU().then((b) => {
            setModelSize(b ? 196 : 77);
            setDevice(b ? 'webgpu' : 'wasm');
        });
    }, []);

    // We use the `useEffect` hook to setup the worker as soon as the `App` component is mounted.
    useEffect(() => {
        if (!worker.current) {
            // Create the worker if it does not yet exist.
            worker.current = new Worker(new URL('./worker.js', import.meta.url), {
                type: 'module'
            });
        }

        // Create a callback function for messages from the worker thread.
        const onMessageReceived = (e) => {
            switch (e.data.status) {
                case 'loading':
                    // Model file start load: add a new progress item to the list.
                    setStatus('loading');
                    setLoadingMessage(e.data.data);
                    break;

                case 'initiate':
                    setProgressItems(prev => [...prev, e.data]);
                    break;

                case 'progress':
                    // Model file progress: update one of the progress items.
                    setProgressItems(
                        prev => prev.map(item => {
                            if (item.file === e.data.file) {
                                return { ...item, ...e.data }
                            }
                            return item;
                        })
                    );
                    break;

                case 'done':
                    // Model file loaded: remove the progress item from the list.
                    setProgressItems(
                        prev => prev.filter(item => item.file !== e.data.file)
                    );
                    break;

                case 'loaded':
                    // Pipeline ready: the worker is ready to accept messages.
                    setStatus('ready');
                    break;

                case 'complete':
                    setResult(e.data.result);
                    setTime(e.data.time);
                    setStatus('ready');
                    break;
            }
        };

        // Attach the callback function as an event listener.
        worker.current.addEventListener('message', onMessageReceived);

        // Define a cleanup function for when the component is unmounted.
        return () => {
            worker.current.removeEventListener('message', onMessageReceived);
        };
    }, []);

    const handleClick = useCallback(() => {
        setResult(null);
        setTime(null);
        if (status === null) {
            setStatus('loading');
            worker.current.postMessage({ type: 'load', data: { device } });
        } else {
            setStatus('running');
            worker.current.postMessage({
                type: 'run', data: { audio, language }
            });
        }
    }, [status, audio, language, device]);

    return (
        <div className="flex flex-col h-screen mx-auto text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 max-w-[600px]">

            {status === 'loading' && (
                <div className="flex justify-center items-center fixed w-screen h-screen bg-black z-10 bg-opacity-[92%] top-0 left-0">
                    <div className="w-[500px]">
                        <p className="text-center mb-1 text-white text-md">{loadingMessage}</p>
                        {progressItems.map(({ file, progress, total }, i) => (
                            <Progress key={i} text={file} percentage={progress} total={total} />
                        ))}
                    </div>
                </div>
            )}
            <div className="my-auto">
                <div className="flex flex-col items-center mb-2 text-center">
                    <h1 className="text-5xl font-bold mb-2">Whisper Diarization</h1>
                    <h2 className="text-xl font-semibold">In-browser automatic speech recognition w/ <br />word-level timestamps and speaker segmentation</h2>
                </div>

                <div className="w-full min-h-[220px] flex flex-col justify-center items-center">
                    {
                        !audio && (
                            <p className="mb-2">
                                You are about to download <a href="https://huggingface.co/onnx-community/whisper-base_timestamped" target="_blank" rel="noreferrer" className="font-medium underline">whisper-base</a> and <a href="https://huggingface.co/onnx-community/pyannote-segmentation-3.0" target="_blank" rel="noreferrer" className="font-medium underline">pyannote-segmentation-3.0</a>,
                                two powerful speech recognition models for generating word-level timestamps across 100 different languages and speaker segmentation, respectively.
                                Once loaded, the models ({modelSize}MB + 6MB) will be cached and reused when you revisit the page.<br />
                                <br />
                                Everything runs locally in your browser using <a href="https://huggingface.co/docs/transformers.js" target="_blank" rel="noreferrer" className="underline">🤗&nbsp;Transformers.js</a> and ONNX Runtime Web,
                                meaning no API calls are made to a server for inference. You can even disconnect from the internet after the model has loaded!
                            </p>
                        )
                    }

                    <div className="flex flex-col w-full m-3 max-w-[520px]">
                        <span className="text-sm mb-0.5">Input audio/video</span>
                        <MediaInput
                            ref={mediaInputRef}
                            className="flex items-center border rounded-md cursor-pointer min-h-[100px] max-h-[500px] overflow-hidden"
                            onInputChange={(audio) => {
                                setResult(null);
                                setAudio(audio);
                            }}
                            onTimeUpdate={(time) => setCurrentTime(time)}
                        />
                    </div>

                    <div className="relative w-full flex justify-center items-center">
                        <button
                            className="border px-4 py-2 rounded-lg bg-blue-400 text-white hover:bg-blue-500 disabled:bg-blue-100 disabled:cursor-not-allowed select-none"
                            onClick={handleClick}
                            disabled={status === 'running' || (status !== null && audio === null)}
                        >
                            {status === null ? 'Load model' :
                                status === 'running'
                                    ? 'Running...'
                                    : 'Run model'
                            }
                        </button>

                        {status !== null &&
                            <div className='absolute right-0 bottom-0'>
                                <span className="text-xs">Language:</span>
                                <br />
                                <LanguageSelector className="border rounded-lg p-1 max-w-[100px]" language={language} setLanguage={setLanguage} />
                            </div>
                        }
                    </div>

                    {
                        result && time && (
                            <>
                                <div className="w-full mt-4 border rounded-md">
                                    <Transcript
                                        className="p-2 max-h-[200px] overflow-y-auto scrollbar-thin select-none"
                                        transcript={result.transcript}
                                        segments={result.segments}
                                        currentTime={currentTime}
                                        setCurrentTime={(time) => {
                                            setCurrentTime(time);
                                            mediaInputRef.current.setMediaTime(time);
                                        }}
                                    />
                                </div>
                                <p className="text-sm text-gray-600 text-end p-1">Generation time: <span className="text-gray-800 font-semibold">{time.toFixed(2)}ms</span></p>
                            </>
                        )
                    }
                </div>
            </div>
        </div >
    )
}

export default App

// whisper-speaker-diarization/src/App.svelte
<script>
  import { onMount, onDestroy } from 'svelte';
  import { writable } from 'svelte/store';
  import Progress from './components/Progress.svelte';
  import MediaInput from './components/MediaInput.svelte';
  import Transcript from './components/Transcript.svelte';
  import LanguageSelector from './components/LanguageSelector.svelte';

  let worker;
  const status = writable(null);
  const loadingMessage = writable('');
  const progressItems = writable([]);
  const audio = writable(null);
  const language = writable('en');
  const result = writable(null);
  const time = writable(null);
  const currentTime = writable(0);
  const device = writable('webgpu');
  const modelSize = writable(196);

  async function hasWebGPU() {
    if (!navigator.gpu) {
      return false;
    }
    try {
      const adapter = await navigator.gpu.requestAdapter();
      return !!adapter;
    } catch (e) {
      return false;
    }
  }

  onMount(async () => {
    const webgpuAvailable = await hasWebGPU();
    modelSize.set(webgpuAvailable ? 196 : 77);
    device.set(webgpuAvailable ? 'webgpu' : 'wasm');

    if (!worker) {
      worker = new Worker(new URL('./worker.js', import.meta.url), {
        type: 'module'
      });
    }

    const onMessageReceived = (e) => {
      switch (e.data.status) {
        case 'loading':
          status.set('loading');
          loadingMessage.set(e.data.data);
          break;
        case 'initiate':
          progressItems.update(items => [...items, e.data]);
          break;
        case 'progress':
          progressItems.update(items => items.map(item => {
            if (item.file === e.data.file) {
              return { ...item, ...e.data };
            }
            return item;
          }));
          break;
        case 'done':
          progressItems.update(items => items.filter(item => item.file !== e.data.file));
          break;
        case 'loaded':
          status.set('ready');
          break;
        case 'complete':
          result.set(e.data.result);
          time.set(e.data.time);
          status.set('ready');
          break;
      }
    };

    worker.addEventListener('message', onMessageReceived);

    return () => {
      worker.removeEventListener('message', onMessageReceived);
    };
  });

  function handleClick() {
    result.set(null);
    time.set(null);
    if (status === null) {
      status.set('loading');
      worker.postMessage({ type: 'load', data: { device } });
    } else {
      status.set('running');
      worker.postMessage({
        type: 'run', data: { audio, language }
      });
    }
  }
</script>

<div class="flex flex-col h-screen mx-auto text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900 max-w-[600px]">
  {#if $status === 'loading'}
    <div class="flex justify-center items-center fixed w-screen h-screen bg-black z-10 bg-opacity-[92%] top-0 left-0">
      <div class="w-[500px]">
        <p class="text-center mb-1 text-white text-md">{$loadingMessage}</p>
        {#each $progressItems as { file, progress, total }, i}
          <Progress {file} {progress} {total} {i} />
        {/each}
      </div>
    </div>
  {/if}
  <div class="my-auto">
    <div class="flex flex-col items-center mb-2 text-center">
      <h1 class="text-5xl font-bold mb-2">Whisper Diarization</h1>
      <h2 class="text-xl font-semibold">In-browser automatic speech recognition w/ <br />word-level timestamps and speaker segmentation</h2>
    </div>

    <div class="w-full min-h-[220px] flex flex-col justify-center items-center">
      {#if !$audio}
        <p class="mb-2">
          You are about to download <a href="https://huggingface.co/onnx-community/whisper-base_timestamped" target="_blank" rel="noreferrer" class="font-medium underline">whisper-base</a> and <a href="https://huggingface.co/onnx-community/pyannote-segmentation-3.0" target="_blank" rel="noreferrer" class="font-medium underline">pyannote-segmentation-3.0</a>,
          two powerful speech recognition models for generating word-level timestamps across 100 different languages and speaker segmentation, respectively.
          Once loaded, the models ({$modelSize}MB + 6MB) will be cached and reused when you revisit the page.<br />
          <br />
          Everything runs locally in your browser using <a href="https://huggingface.co/docs/transformers.js" target="_blank" rel="noreferrer" class="underline">🤗&nbsp;Transformers.js</a> and ONNX Runtime Web,
          meaning no API calls are made to a server for inference. You can even disconnect from the internet after the model has loaded!
        </p>
      {/if}

      <div class="flex flex-col w-full m-3 max-w-[520px]">
        <span class="text-sm mb-0.5">Input audio/video</span>
        <MediaInput
          class="flex items-center border rounded-md cursor-pointer min-h-[100px] max-h-[500px] overflow-hidden"
          on:inputChange={(e) => {
            result.set(null);
            audio.set(e.detail);
          }}
          on:timeUpdate={(e) => currentTime.set(e.detail)}
        />
      </div>

      <div class="relative w-full flex justify-center items-center">
        <button
          class="border px-4 py-2 rounded-lg bg-blue-400 text-white hover:bg-blue-500 disabled:bg-blue-100 disabled:cursor-not-allowed select-none"
          on:click={handleClick}
          disabled={$status === 'running' || ($status !== null && $audio === null)}
        >
          {#if $status === null}
            Load model
          {:else if $status === 'running'}
            Running...
          {:else}
            Run model
          {/if}
        </button>

        {#if $status !== null}
          <div class='absolute right-0 bottom-0'>
            <span class="text-xs">Language:</span>
            <br />
            <LanguageSelector class="border rounded-lg p-1 max-w-[100px]" {language} />
          </div>
        {/if}
      </div>

      {#if $result && $time}
        <div class="w-full mt-4 border rounded-md">
          <Transcript
            class="p-2 max-h-[200px] overflow-y-auto scrollbar-thin select-none"
            {transcript}={$result.transcript}
            {segments}={$result.segments}
            {currentTime}={$currentTime}
            on:setCurrentTime={(e) => {
              currentTime.set(e.detail);
              mediaInputRef.current.setMediaTime(e.detail);
            }}
          />
        </div>
        <p class="text-sm text-gray-600 text-end p-1">Generation time: <span class="text-gray-800 font-semibold">{$time.toFixed(2)}ms</span></p>
      {/if}
    </div>
  </div>
</div>
